services:
  pgsql:
    container_name: jerry-pgsql
    image: jerry2/postgres:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./pgsql/postgresql/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=jerry

  pgadmin:
    container_name: jerry-pgadmin
    image: dpage/pgadmin4:8.4
    restart: always
    ports:
      - 60081:80
    volumes:
      - ./pgadmin/pgadmin:/var/lib/pgadmin
      - ./pgadmin/config_local.py:/pgadmin4/config_local.py
      - ./pgadmin/servers.json:/pgadmin4/servers.json
      - ./pgadmin/preferences.json:/pgadmin4/preferences.json
    environment:
      - PGADMIN_DEFAULT_EMAIL=xinyu.liu@getjerry.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin

  mongo:
    container_name: jerry-mongo
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017

  mongo-express:
    container_name: jerry-mongo-express
    image: mongo-express
    restart: always:latest
    ports:
      - 60082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: jerry
      ME_CONFIG_MONGODB_ADMINPASSWORD: jerry
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
