services:
  mysql:
    container_name: caixuan-mysql
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=mysql@wsl
      - MYSQL_USER=caixuan
      - MYSQL_PASSWORD=xj1Ix6WzQENITbFR
      - MYSQL_DATABASE=caixuan
  phpmyadmin:
    container_name: caixuan-pma
    image: phpmyadmin:latest
    restart: always
    ports:
      - 60080:80
    environment:
      - PMA_ARBITRARY=1
